= mill-kotlin - Kotlin compiler support for mill
:version: 0.0.1
:kotlinVersion: 1.3.61
:projectHome: https://github.com/lefou/mill-kotlin
:mill-version: 0.5.7
:toc:
:toc-placement: preamble

ifdef::env-github[]
image:https://travis-ci.org/lefou/mill-kotlin.svg?branch=master["Build Status", link="https://travis-ci.org/lefou/mill-kotlin"]
endif::[]

Documentation for mill-kotlin, a mill plugin to support the https://kotlinlang.org/[Kotlin language and compiler].

== Quickstart

Mill version {mill-version} or newer is required.

[source,scala,subs="attributes,verbatim"]
----
import mill._
import mill.scalalib._
import mill.define._

// Load the plugin from Maven Central via ivy/coursier
import $ivy.`de.tototec::de.tobiasroeser.mill.kotlin:{version}`, de.tobiasroeser.mill.kotlin._

object main extends KotlinModule {

  // Select the Kotlin version
  def kotlinVersion = T{ "{kotlinVersion}" }

  // Set additional Kotlin compiler options, e.g. the language level and annotation processor
  // Run `mill main.kotlincHelp` to get a list of supported options
  def kotlincOptions = Seq("-verbose")

}
----

== Configuration

To target the JVM (kotlin-jvm), our module needs to extend `de.tobiasroeser.mill.kotlin.KotlinModule` which itself extends `mill.scalalib.JavaModule`.

For convenience, you may derive your unit test projects from `de.tobiasroeser.mill.kotlin.KotlinModule.Tests` trait.

The module trait `de.tobiasroeser.mill.kotlin.KotlinModule` has the following configuration options (over those from `mill.scalalib.JavaModule`).

`def kotlinVersion: T[String]`::
  The Kotlin version to be used (for API and Language level settings).

`def kotlinCompilerVersion: T[String]`:: The version of the Kotlin compiler to be used.
  Default is derived from `kotlinVersion`.

`def compile: T[CompilationResult]`::
  Compiles all the sources to JVM class files.

`def kotlincOptions: T[Seq[String]]`::
  Additional Kotlin compiler options to be use by `compile`.

`def ivyDeps: T[Agg[Dep]]`::
  The compile and runtime dependencies.

`def kotlincHelp(args: String*): Command[Unit]`::
  Runs the Kotlin compiler with the `-help` argument to show you the built-in cmdline help.
  You might want to add additional arguments like `-X` to see extra help.

`def kotlinCompilerIvyDeps: T[Agg[Dep]]`::
  The Ivy/Coursier dependencies resembling the Kotlin compiler.
  Default is derived from `kotlinCompilerVersion`.

`def kotlinCompilerClasspath: T[Seq[PathRef]]`::
  The Java classpath resembling the Kotlin compiler.
  Default is derived from `kotlinCompilerIvyDeps`.

`trait Tests extends TestModule with KotlinTestModule`::
  A test sub-module linked to its parent module best suited for unit-tests.

== Version Compatibility Matrix

Mill is still in active development, and has no stable API yet.
Hence, not all mill-kotlin versions work with every mill version.

The following table shows a matrix of compatible mill and mill-kotlin versions.

.Version Compatibility Matrix
[options="header"]
|===
| mill-kotlin | mill
| 0.0.1 | 0.5.7
|===

== Download

You can download binary releases from https://search.maven.org/search?q=a:de.tobiasroeser.mill.kotlin_2.12%20g:de.tototec[Maven Central].

== License

Apache License, version 2

== Supporters

Thanks to https://iba-cg.de/[iba Consulting Gesellschaft mbH & Co KG] for the initial development support.

== About

mill::
  https://github.com/lihaoyi/mill[Mill] is a Scala-based open source build tool.
  In my opinion the best build tool for the JVM.
  It is fast, reliable and easy to understand.

me::
+
--
https://github.com/lefou/[I'm] a professional software developer and love to do open source.
I'm actively developing and maintaining mill as well as https://github.com/lefou?utf8=%E2%9C%93&tab=repositories&q=topic%3Amill&type=&language=[several mill plugins].

If you like my work, please star it on GitHub. You can also support me via https://github.com/sponsors/lefou[GitHub Sponsors].
--

Contributing::
  If you found a bug or have a feature request, please open a {projectHome}/issues[new issue on GitHub].
  I also accept {projectHome}/pulls[pull requests on GitHub].

== Changelog

=== mill-kotlin 0.0.1 - 2020-02-20
:prev-version:
:version: 0.0.1
:github-milestone:

* Initial release
//_See https://github.com/lefou/mill-kotlin/milestone/{github-milestone}?closed=1[milstone {version}]
//and the https://github.com/lefou/mill-kotlin/compare/{prev-version}...{version}[list of commits]_
