on: [push, pull_request]

env:
  PUBLISH_BRANCH: refs/heads/main

jobs: 
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java-version: [1.8, 11]
        targets:
          - __.publishLocal $(pwd)/testRepo
          - "main[_].__.test"
          - "itest[0.9.7].test"
          - "itest[0.9.6].test"
          - "itest[0.9.5].test"
          - "itest[0.9.4].test"
          - "itest[0.9.3].test"
          - "itest[0.8.0].test"
          - "itest[0.7.4].test"
          - "itest[0.7.3].test"
          - "itest[0.7.2].test"
          - "itest[0.7.1].test"
          - "itest[0.7.0].test"
          - "itest[0.6.3].test"
          - "itest[0.6.2].test"
          - "itest[0.6.1].test"
          - "itest[0.6.0].test"
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.os == 'windows-latest' }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - run: ./millw -i ${{ matrix.targets }}

      - run: ./millw __.scoverage.xmlReport

      - name: Upload scoverage reports to codecov.io
        uses: codecov/codecov-action@v1
        with:
          file: ./out/*/scoverage/xmlReport/dest/scoverage.xml
        continue-on-error: true

  publish:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - run: ./millw -i __.publishLocal $(pwd)/testRepo

      - name: Setup GPG secrets for publish
        if: github.ref == env.PUBLISH_BRANCH && github.event_name == 'push'
        run: |
          gpg --version
          cat <(echo "${{ secrets.GPG_SECRET_KEY }}") | base64 --decode | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Publish to Maven Central
        if: github.ref == env.PUBLISH_BRANCH && github.event_name == 'push'
        run: ./millw -i mill.scalalib.PublishModule/publishAll --sonatypeCreds "${{ secrets.SONATYPE_CREDS }}" --gpgArgs "--passphrase=${{ secrets.GPG_SECRET_KEY_PASS }},--batch,--yes,-a,-b,--pinentry-mode,loopback" --publishArtifacts __.publishArtifacts --readTimeout 600000 --release true --signed true

